version: '3.7'

services:
  python:
    image: python:3.8
    environment:
      - ENV=dev
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD=${DISCORD_GUILD}
    volumes:
      - ./:/app/
    working_dir: /app
